name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Setup Pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4

  trigger-staging:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'push'
    env:
      HAS_INFRA_TOKEN: ${{ secrets.INFRA_DISPATCH_TOKEN != '' }}
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        if: env.HAS_INFRA_TOKEN == 'true'
        env:
          COMMIT_SHA: ${{ github.sha }}
        with:
          github-token: ${{ secrets.INFRA_DISPATCH_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'gunk-dev',
              repo: 'infra',
              event_type: 'flux-staging',
              client_payload: {
                sha: process.env.COMMIT_SHA
              }
            });
